name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Create .env file
        run: |
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}" >> .env
          echo "VITE_OPENAI_API_KEY=${{ secrets.VITE_OPENAI_API_KEY }}" >> .env
          
      - name: Verify Environment Variables
        run: |
          if [ -z "${{ secrets.VITE_FIREBASE_API_KEY }}" ]; then
            echo "Error: VITE_FIREBASE_API_KEY is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" ]; then
            echo "Error: VITE_FIREBASE_AUTH_DOMAIN is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VITE_FIREBASE_PROJECT_ID }}" ]; then
            echo "Error: VITE_FIREBASE_PROJECT_ID is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" ]; then
            echo "Error: VITE_FIREBASE_STORAGE_BUCKET is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" ]; then
            echo "Error: VITE_FIREBASE_MESSAGING_SENDER_ID is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VITE_FIREBASE_APP_ID }}" ]; then
            echo "Error: VITE_FIREBASE_APP_ID is not set"
            exit 1
          fi
          
      - name: Build
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 